---
version: '3.3'

services:
  mongo:
    container_name: mongo
    ports:
      - "27017:27017"
    image: mongo
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"

  data:
    container_name: examplehealthdata
    build: data-service
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MAPBOX_ACCESS_TOKEN=<MAPBOX_ACCESS_TOKEN>
      - DATA_SOURCE_API=<DATA_SOURCE_API>

  web:
    container_name: examplehealthweb
    build: web
    ports:
      - "4000:4000"
    depends_on:
      - data
    environment:
      - DATA_SERVER=http://examplehealthdata:3000
